### ISSUE TITLE
ImportError: No module named _pydart_api

### ISSUE THREAD

**Issue by jeffeb3** [sehoonha/pydart#4]
Not sure why this is happening, I was able to run the setup.py develop, but I get this error whenever I try running 'import pydart' or running the examples.

full stack trace:

```
 >>> import pydart
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydart/__init__.py", line 1, in <module>
    from pydart import *
  File "pydart/pydart.py", line 7, in <module>
    import pydart_api as papi
  File "pydart/pydart_api.py", line 28, in <module>
    _pydart_api = swig_import_helper()
  File "pydart/pydart_api.py", line 20, in swig_import_helper
    import _pydart_api
ImportError: No module named _pydart_api
```

**Comment by jeffeb3** [comment]
I'm sorry, I forgot to do the make install step, so it was missing the _pydart_api.so.
